runners:
 ubuntu-runner:
  image: localhost:5000/ubuntu:20.04

jobs:
  say-hello-world:
    runner: ubuntu-runner
    steps:
      - run:
          name: Hello World Step
          command: |
            echo "Hello World"

workflows:
  getting-started:
    jobs:
      - say-hello-world
